apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trifourier

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - backup-cronjob.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "0.1.0"
