apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trifourier-graph-pvc
  namespace: trifourier
  labels:
    app.kubernetes.io/name: trifourier
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
