{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trifourier.fullname" . }}-secrets
  labels:
    {{- include "trifourier.labels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken | quote }}
  SLACK_APP_TOKEN: {{ .Values.secrets.slackAppToken | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.secrets.slackSigningSecret | quote }}
{{- end }}
